{% set data = load_setup_py_data() %}

package:
  name: pcdsdevices
  version: {{ data['version'] }}

source:
  path: ..

build:
  number: 1

requirements:
  build:
    - python {{PY_VER}}*,>=3
    - setuptools

  run:
    - python {{PY_VER}}*,>=3
    # Inspect requirements.txt for the reqs
    {% for spec in data['install_requires'] %}
      {% set ns = namespace(spec=spec) %}
      # Need to add a space before the first symbol. List order matters.
      {% for sep in ['=', '<', '>'] %}
        {% if sep in spec %}
          {% set ns.spec = spec.replace(sep, ' ' + sep) %}
        {% endif %}
      {% endfor %}
    - {{ ns.spec }}
    {% endfor %}

test:
  imports:
    - pcdsdevices

about:
  home: https://github.com/pcdshub/pcdsdevices
  license: SLAC Open License
  summary: IOC definitions for LCLS Beamline Devices
